# This workflow will build a Java project with Gradle
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      # https://github.com/gradle/wrapper-validation-action
      - uses: gradle/wrapper-validation-action@v1
      
      # https://github.com/gradle/gradle-build-action
      - uses: gradle/gradle-build-action@v2.4.2
      
      - name: Build with Gradle Wrapper
        run: ./gradlew build
